version: "3.8"

services:
  app:
    image: spring-boot-app-image
    build: .
    ports:
      - "80:80"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
