name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Velg Java-versjon
          distribution: 'adoptopenjdk'  # Velg Java-distribusjon (f.eks. adoptopenjdk, zulu, openjdk)

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker Image
        run: docker build -t spring-boot-app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push spring-boot-app:latest
