name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Setter opp Java JDK 11
      - name: Set up Java JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Velg Java-versjon
          distribution: 'zulu'  # Velg Java-distribusjon (kan være 'zulu', 'openjdk', eller 'adoptopenjdk')

      # Installer Docker og bygg bilde
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t spring-boot-app:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push spring-boot-app:latest
