name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: {}  # Gjør at du kan kjøre workflow manuelt fra GitHub

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Sjekk ut koden fra repoet
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Debug-utskrift for å kontrollere at AWS-regionen er satt
      - name: Debug AWS Secrets
        run: echo "Using AWS Region: ${{ secrets.AWS_REGION }}"

      # 3️⃣ Konfigurer AWS-legitimasjonene for GitHub Actions
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: github-actions  # Valgfritt, men nyttig for logging

      # 4️⃣ Logg inn til Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 5️⃣ Definer ECR repository URL
      - name: Define ECR repository URL
        run: echo "ECR_REPOSITORY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/coursera/spring-boot-docker" >> $GITHUB_ENV

      # 6️⃣ Bygg Docker-imaget
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:latest .

      # 7️⃣ Push Docker-imaget til Amazon ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REPOSITORY:latest

      # 8️⃣ Skriv ut ferdig melding
      - name: Deployment Complete
        run: echo "Docker image pushed successfully to ECR!"
