name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug AWS Secrets
        run: |
          echo "AWS_REGION=${{ secrets.AWS_REGION }}"
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}"
          if [[ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]]; then 
            echo "❌ AWS_ACCOUNT_ID is EMPTY! Check GitHub Secrets."
            exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define ECR repository URL
        run: |
          echo "ECR_REPOSITORY=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/coursera/spring-boot-docker" >> $GITHUB_ENV
          cat $GITHUB_ENV  # Debugging - sjekker at verdien er riktig

      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$GITHUB_SHA .

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REPOSITORY:$GITHUB_SHA

      - name: Deployment Complete
        run: echo "✅ Docker image pushed successfully to ECR!"
